general {
  immediate_render = false
}

background {
  monitor =
  path = screenshot
  color = rgba(25,20,20,1.0)

  blur_passes = 1
  blur_size = 5

  noise = 0.001
  contrast = 0.5
  brightness = 0.5
  vibrancy = 0.5
}

label {
  monitor =
  text = $TIME
  color = rgba(200,200,200,1.0)
  font_size = 100
  font_family = JetBrainsMono Nerd Font Mono Bold
  position = 0, 80
  halign = center
  valign = center
}

input-field {
  monitor =
  size = 200, 50
  outline_thickness = 5

  dots_size = 0.33
  dots_center = true
  inner_color = rgba(235, 219, 178, 0.5)
  outer_color = rgba(60, 56, 54, 1)
  font_color = rgba(40,40, 40, 1)

  fade_on_empty = true
  placeholder_text = <i>Input Password..</i>
  hide_input = false

  position = 0, -20
  halign = center
  valign = center
}
listener {
  timeout = 360                                # 6 min.
    on-timeout = brightnessctl -s set 10         # set monitor backlight to minimum, avoid 0 on OLED monitor.
    on-resume = brightnessctl -r                 # monitor backlight restore.
}
listener {
  timeout = 330                                                     # 5.5min
    on-timeout = hyprctl dispatch dpms off                            # screen off when timeout has passed
    on-resume = hyprctl dispatch dpms on && brightnessctl -r          # screen on when activity is detected after timeout has fired.
}
listener {
  timeout = 1800                                # 30min
    on-timeout = systemctl suspend                # suspend pc
}
